"""initial migration

Revision ID: 1f4d64d1f3ba
Revises: dfcdbef3d0de
Create Date: 2021-03-28 16:51:54.475303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f4d64d1f3ba'
down_revision = 'dfcdbef3d0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nk_received_request', sa.Column('contacte', sa.String(length=50), nullable=True))
    op.drop_index('email', table_name='nk_received_request')
    op.create_unique_constraint(None, 'nk_received_request', ['contacte'])
    op.create_foreign_key(None, 'nk_received_request', 'nk_register_doctor', ['doctor'], ['id'])
    op.drop_column('nk_received_request', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nk_received_request', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'nk_received_request', type_='foreignkey')
    op.drop_constraint(None, 'nk_received_request', type_='unique')
    op.create_index('email', 'nk_received_request', ['email'], unique=True)
    op.drop_column('nk_received_request', 'contacte')
    # ### end Alembic commands ###
