"""initial migration

Revision ID: 53683dc08330
Revises: f9effd504b34
Create Date: 2021-03-28 17:03:16.087838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53683dc08330'
down_revision = 'f9effd504b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nk_received_request', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nk_received_request', 'description')
    # ### end Alembic commands ###
