"""initial migration

Revision ID: b0269fb680a8
Revises: 53683dc08330
Create Date: 2021-03-28 17:29:39.233550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0269fb680a8'
down_revision = '53683dc08330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nk_received_request', sa.Column('onhold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nk_received_request', 'onhold')
    # ### end Alembic commands ###
