"""initial migration

Revision ID: e49370349246
Revises: b0269fb680a8
Create Date: 2021-04-02 13:48:25.795352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49370349246'
down_revision = 'b0269fb680a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nk_register_doctor', sa.Column('function', sa.String(length=200), nullable=True))
    op.add_column('nk_register_doctor', sa.Column('picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nk_register_doctor', 'picture')
    op.drop_column('nk_register_doctor', 'function')
    # ### end Alembic commands ###
