"""initial migration

Revision ID: f9effd504b34
Revises: 1f4d64d1f3ba
Create Date: 2021-03-28 16:54:56.515850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9effd504b34'
down_revision = '1f4d64d1f3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contacte', table_name='nk_received_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('contacte', 'nk_received_request', ['contacte'], unique=True)
    # ### end Alembic commands ###
